version: '3'
services:
    server:
        build: .
        image: moviesurfer_server:latest
        command: npm start
        ports:
          - '8080:8080'
        volumes:
          - '.:/usr/src/app'
          - /usr/src/app/node_modules
