version: '3'
services:
    front-end:
        build: .
        image: moviesurfer_server:latest
        command: npm start
        ports:
          - '8000:3000'
        volumes:
          - '.:/usr/src/app'
          - /usr/src/app/node_modules
