version: '3'
services:
  api:
    build:
      context: .
      target: base
    container_name: moviesurfer_api
    image: moviesurfer_api
    command: npm start
    ports:
    - '8080:8080'
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
